{"name": "test_login_failture", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_feature_story.TestLogin object at 0x0000028E79401A60>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failture(self):\n        with allure.step(\"点击用户名\"):\n            print(\"请输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"请输入密码\")\n        print(\"点击登陆\")\n        with allure.step(\"点击登陆之后登陆失败\"):\n>           assert '1'==1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:29: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1608527201698, "stop": 1608527201698}, {"name": "点击密码", "status": "passed", "start": 1608527201698, "stop": 1608527201698}, {"name": "点击登陆之后登陆失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\Users\\limandi\\PycharmProjects\\hogwarts_lg4\\python1029_alluredemo\\result\\test_feature_story.py\", line 29, in test_login_failture\n    assert '1'==1\n"}, "start": 1608527201698, "stop": 1608527201698}], "attachments": [{"name": "stdout", "source": "4b05e0de-1abb-4747-b15b-1704d525246a-attachment.txt", "type": "text/plain"}], "start": 1608527201698, "stop": 1608527201699, "uuid": "b6a8e312-3658-43e4-b591-057a8bd52797", "historyId": "5f122b9cb20dd88a67f39a89071c8190", "testCaseId": "155e384787284014d9a76fc89082e581", "fullName": "test_feature_story.TestLogin#test_login_failture", "labels": [{"name": "feature", "value": "登陆模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "nb2-hz20113336"}, {"name": "thread", "value": "8364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}