{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_alluredemo1.py:19: Exception"}, "start": 1608526144267, "stop": 1608526144268, "uuid": "43ac5f3a-2d58-484b-8476-a605961f3336", "historyId": "62e3d0efc8226834b589024da8762ee8", "testCaseId": "17acedbab6e0d57f20e780d7d6084ef4", "fullName": "test_alluredemo1#test_broken", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "nb2-hz20113336"}, {"name": "thread", "value": "19676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}